### ISSUE TITLE
Entering a coordinate

### ISSUE THREAD

**Issue by jonas-jaderberg** [ArnoldV/Our.Umbraco.GMaps#112]
I need to be able to entering a coordinate e.g. 59.31693, 18.07376. This does not work now. Debugging the code I can see that the problem is the vm.searchValue is empty.

```	
autocomplete.addListener('place_changed', function () {
vm.marker.setVisible(false)
var place = autocomplete.getPlace()
if (!place.geometry) {
	// User entered the name of a Place that was not suggested and pressed the Enter key, or the Place Details request failed.
	var coordTest = parseCoordinates(vm.searchedValue, false)
	if (coordTest) {
		$scope.address.coordinates = coordTest
	}
..
```
If I change to
```
var coordTest = parseCoordinates($scope.searchedValue, false)
```
then I can get the map to display the coordinate,
But, if I had a place before I also have to clean the place/address and then I have to save.
So to get ut to work I have to change like this

```
autocomplete.addListener('place_changed', function () {
       vm.marker.setVisible(false)
	var place = autocomplete.getPlace()
        if (!place.geometry) {
	        // User entered the name of a Place that was not suggested and pressed the Enter key, or the Place Details request failed.
	        var coordTest = parseCoordinates($scope.searchedValue, false)
	        if (coordTest) {
		        $scope.address = {}
		        $scope.address.coordinates = coordTest
	        }
	        initMapMarker($scope.address.coordinates)
	        saveData()
	        return
        }
...
```
I don't know is it a bug that you cannot search / enter a coordinate? I got it working but not sure if I did the the right way.

**Comment by robertjf** [comment]
Thanks @jonas-jaderberg - good find.  Fixed in the 2.0.7 upcoming release.

**Comment by jonas-jaderberg** [comment]
I have tested 2.0.7 now but it does not solve this issue. If you enter a coordinate the pin will not move to the coordinate.
I just briefly checked the code and I think it has to do with the code that differs from mine
```
 initMapMarker($scope.address.coordinates)
	        saveData()
	        return
```

**Comment by robertjf** [comment]
@jonas-jaderberg I just tested this by upgrading an existing project to the latest version of GMaps (2.0.7) - make sure you've re-compiled after the upgrade - you should see this as well if the upgrade is succesful (i.e. the addition of the "Reset Center" action):

![image](https://user-images.githubusercontent.com/818101/177004144-bacd6de1-8581-49c3-bf26-f02558f3c221.png)

It's working in this project, with the exception of the "Pin" and "Center" values don't update until you've exited the textbox (fix pending in next release).

Also check that you haven't overridden the nuget package version of the controller.

**Comment by jonas-jaderberg** [comment]
Yes sorry, I tried again, rebuild and did a har refresh and now it works.
